// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/bookandmusic/love-girl/internal/repo"
	"github.com/bookandmusic/love-girl/internal/server"
	"github.com/bookandmusic/love-girl/provider/infra"
)

// Injectors from wire.go:

func InitApp() (*server.App, func(), error) {
	appConfig, err := infra.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := infra.ProvideLogger(appConfig)
	ginEngine := ProvideGinEngine(appConfig, logger)
	jwt := infra.ProvideJWT(appConfig)
	authMiddleware := infra.ProvideAuthMiddleware(jwt)
	gormLogger := infra.ProvideGormLogger(appConfig, logger)
	db, err := infra.ProvideDB(appConfig, gormLogger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(db, jwt)
	fileRepo := repo.NewFileRepo(db)
	storage, err := ProvideStorage(appConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	fileService := ProvideFileService(logger, storage, fileRepo, appConfig)
	userService := ProvideUserService(logger, userRepo, fileRepo, fileService, storage, appConfig, jwt)
	userHandler := ProvideUserHandler(userService)
	healthHandler := ProvideHealthHandler()
	fileHandler := ProvideFileHandler(fileService)
	settingRepo := repo.NewSettingRepo(db)
	albumRepo := repo.NewAlbumRepo(db)
	placeRepo := repo.NewPlaceRepo(db)
	momentRepo := repo.NewMomentRepo(db)
	wishRepo := repo.NewWishRepo(db)
	systemService := ProvideSystemService(logger, userRepo, settingRepo, albumRepo, placeRepo, momentRepo, wishRepo, fileService, appConfig, jwt)
	systemHandler := ProvideSystemHandler(systemService)
	momentService := ProvideMomentService(logger, momentRepo, fileService)
	momentHandler := ProvideMomentHandler(momentService)
	anniversaryRepo := repo.NewAnniversaryRepo(db)
	anniversaryService := ProvideAnniversaryService(logger, anniversaryRepo)
	anniversaryHandler := ProvideAnniversaryHandler(anniversaryService)
	placeService := ProvidePlaceService(logger, placeRepo, fileService)
	placeHandler := ProvidePlaceHandler(placeService)
	wishService := ProvideWishService(logger, wishRepo)
	wishHandler := ProvideWishHandler(wishService, jwt)
	albumService := ProvideAlbumService(logger, albumRepo, fileService)
	albumHandler := ProvideAlbumHandler(albumService)
	v := ProvideHandlers(userHandler, healthHandler, fileHandler, systemHandler, momentHandler, anniversaryHandler, placeHandler, wishHandler, albumHandler)
	staticHandler := ProvideStaticHandler()
	swaggerHandler := ProvideSwaggerHandler()
	v2 := ProvideStaticHandlers(staticHandler, swaggerHandler)
	engine := ProvideRouter(appConfig, ginEngine, authMiddleware, v, v2)
	error2 := infra.ProvideMigrate(db, logger)
	app := ProvideApp(appConfig, logger, engine, error2)
	return app, func() {
	}, nil
}
