package config

// AppConfig 根配置
type AppConfig struct {
	App        AppConfigApp     `mapstructure:"app" validate:"required"`
	DataDir    string           `mapstructure:"data_dir"` // 数据目录，统一管理所有数据文件
	Server     ServerConfig     `mapstructure:"server" validate:"required"`
	Log        LogConfig        `mapstructure:"log" validate:"required"`
	DataSource DataSourceConfig `mapstructure:"datasource" validate:"required"`
	JWT        JWTConfig        `mapstructure:"jwt"`
	Storage    StorageConfig    `mapstructure:"storage" validate:"required"`
	ImageProxy ImageProxyConfig `mapstructure:"image_proxy"`
}

// DataPaths 数据目录路径（运行时计算）
type DataPaths struct {
	ConfigDir string // 配置文件目录
	UploadDir string // 上传文件目录
	DBFile    string // 数据库文件路径
}

// GetDataPaths 获取数据目录路径
func (c *AppConfig) GetDataPaths() *DataPaths {
	dataDir := c.DataDir
	if dataDir == "" {
		dataDir = "./data"
	}

	return &DataPaths{
		ConfigDir: dataDir + "/configs",
		UploadDir: dataDir + "/uploads",
		DBFile:    dataDir + "/love-girl.db",
	}
}

// AppConfigApp 应用基本信息
type AppConfigApp struct {
	Name string `mapstructure:"name" validate:"required"`
	Env  string `mapstructure:"env" validate:"required,oneof=dev test prod"`
}

// ServerConfig HTTP 服务配置
type ServerConfig struct {
	Addr           string     `mapstructure:"addr" validate:"required"`
	Mode           string     `mapstructure:"mode" validate:"required,oneof=debug release test"`
	InternalURL    string     `mapstructure:"internal_url"`    // 内网地址，ImageProxy 访问 Gin 用（可选）
	RequestTimeout int        `mapstructure:"request_timeout"` // 请求处理超时（秒），0 表示不限制
	CORS           CORSConfig `mapstructure:"cors"`
}

// CORSConfig CORS 配置
type CORSConfig struct {
	AllowAllOrigins bool     `mapstructure:"allow_all_origins"` // 是否允许所有来源，默认 true
	AllowOrigins    []string `mapstructure:"allow_origins"`     // 允许的来源列表（AllowAllOrigins=false 时生效）
	AllowMethods    []string `mapstructure:"allow_methods"`     // 允许的 HTTP 方法
	AllowHeaders    []string `mapstructure:"allow_headers"`     // 允许的请求头
}

// LogConfig 日志配置
type LogConfig struct {
	Level  string `mapstructure:"level" validate:"required,oneof=debug info warn error"`
	Format string `mapstructure:"format"` // json, text (默认 text)
	Output string `mapstructure:"output"` // stdout 或文件路径 (默认 stdout)
}

// DataSourceConfig 数据源配置
type DataSourceConfig struct {
	Database DatabaseConfig `mapstructure:"database" validate:"required"`
}

// DatabaseConfig 数据库配置
type DatabaseConfig struct {
	Driver string `mapstructure:"driver" validate:"required,oneof=sqlite mysql postgres"`
	DSN    string `mapstructure:"dsn"` // 数据库连接串（MySQL/PostgreSQL 必填，SQLite 自动使用 data_dir）
}

// JWTConfig JWT 配置
type JWTConfig struct {
	Secret         string `mapstructure:"secret"` // JWT 密钥，未配置时自动生成
	Issuer         string `mapstructure:"issuer"` // JWT 签发者
	Expire         int64  `mapstructure:"expire"` // Token 有效期（秒）
	_autoGenerated bool   // 内部标记：Secret 是否为自动生成
}

// StorageConfig 存储配置
type StorageConfig struct {
	Backend string               `mapstructure:"backend" validate:"required,oneof=local s3 webdav"`
	S3      *S3StorageConfig     `mapstructure:"s3"`
	WebDAV  *WebDAVStorageConfig `mapstructure:"webdav"`
	// Local 存储路径由 data_dir 自动计算，不支持配置
}

// ImageProxyConfig 图片代理（如 imgproxy / thumbor）
type ImageProxyConfig struct {
	InternalURL string `mapstructure:"internal_url"` // 内网地址，Gin 转发时使用
	PublicURL   string `mapstructure:"public_url"`   // 公开地址，前端直接访问（可选）
}

// S3StorageConfig S3 / S3-compatible 存储
type S3StorageConfig struct {
	UseSSL   bool   `mapstructure:"use_ssl"`
	Endpoint string `mapstructure:"endpoint"`
	Region   string `mapstructure:"region"`
	Bucket   string `mapstructure:"bucket"`

	Credentials struct {
		AccessKeyID     string `mapstructure:"access_key_id"`
		SecretAccessKey string `mapstructure:"secret_access_key"`
	} `mapstructure:"credentials"`

	PublicURL     string `mapstructure:"public_url"`     // 公开访问地址（可选）
	PresignEnable bool   `mapstructure:"presign_enable"` // 是否启用预签名
	PresignExpire int64  `mapstructure:"presign_expire" validate:"omitempty,min=1"`
}

// WebDAVStorageConfig WebDAV 存储
type WebDAVStorageConfig struct {
	Endpoint  string `mapstructure:"endpoint"`
	BasePath  string `mapstructure:"base_path"`
	PublicURL string `mapstructure:"public_url"` // 公开访问地址（可选）

	Auth struct {
		Username string `mapstructure:"username"`
		Password string `mapstructure:"password"`
	} `mapstructure:"auth"`
}
